version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Adjust as needed
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  fscrawler:
    image: dadoonet/fscrawler
    container_name: fscrawler
    volumes:
      - ./documents/cohen:/usr/share/fscrawler/cohen
#      - ./folder2:/usr/share/fscrawler/folder2
      - ./fscrawler_config:/usr/share/fscrawler/config
    environment:
      - "FSCRAWLER_INDEX_1=cohen"
      - "FSCRAWLER_URL=http://elasticsearch:9200"
    depends_on:
      - elasticsearch

volumes:
  esdata:
