version: '3.8'

services:
  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - ./elasticsearch/data/certs:/usr/share/elasticsearch/config/certs
      - ./setup/scripts/:/usr/share/elasticsearch/scripts
    user: "0"
    env_file:
      - .env
    command: ["/bin/bash", "/usr/share/elasticsearch/scripts/setup.sh"]

    healthcheck:
      test: ["CMD-SHELL", "test -f /usr/local/bin/setup_done || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - es-net

  es01:
    container_name: es01
    depends_on:
      setup:
        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - ./elasticsearch/data/certs:/usr/share/elasticsearch/config/certs
      - ./elasticsearch/data/es01/data:/usr/share/elasticsearch/data
    env_file:
      - .env
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
#      - discovery.type=single-node
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es01/es01.key
      - xpack.security.http.ssl.certificate=certs/es01/es01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es01/es01.key
      - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - es-net

  es02:
    container_name: es02
    depends_on:
      setup:
        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - ./elasticsearch/data/certs:/usr/share/elasticsearch/config/certs
      - ./elasticsearch/data/es02/data:/usr/share/elasticsearch/data
    env_file:
      - .env
    environment:
      - node.name=es02
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es02/es02.key
      - xpack.security.http.ssl.certificate=certs/es02/es02.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es02/es02.key
      - xpack.security.transport.ssl.certificate=certs/es02/es02.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - es-net

  es03:
    container_name: es03
    depends_on:
      setup:
        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - ./elasticsearch/data/certs:/usr/share/elasticsearch/config/certs
      - ./elasticsearch/data/es03/data:/usr/share/elasticsearch/data
    env_file:
      - .env
    environment:
      - node.name=es03
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es03/es03.key
      - xpack.security.http.ssl.certificate=certs/es03/es03.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es03/es03.key
      - xpack.security.transport.ssl.certificate=certs/es03/es03.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - es-net

  pipeline-loader:
    depends_on:
      es03:
        condition: service_healthy
    image: alpine
    volumes:
      - ./elasticsearch/settings:/usr/local/bin/config/elasticsearch
      - ./fscrawler/config:/usr/local/bin/config/fscrawler
    entrypoint: ["/bin/sh", "/usr/local/bin/config/elasticsearch/initialize_index.sh"]
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "test -f /usr/local/bin/init_pipeline_done || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - es-net

  kibana:
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
      es03:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    volumes:
      - ./elasticsearch/data/certs:/usr/share/kibana/config/certs
      - kibanadata:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://es01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - es-net

  fscrawler:
    depends_on:
      pipeline-loader:
        condition: service_healthy
      es03:
        condition: service_healthy
    build:
      context: .
      dockerfile: fscrawler/Dockerfile
    container_name: fscrawler
    restart: always
    volumes:
      - ../../../mnt/expert_share/clients:/usr/share/fscrawler/files # ../../../ for shared volume
      - ./elasticsearch/data/certs:/usr/share/fscrawler/certs
      - ./fscrawler/config:/root/.fscrawler
      - ./fscrawler/logs:/usr/share/fscrawler/logs
      - ./fscrawler/external:/usr/share/fscrawler/external
      - ./fscrawler/log4j2.properties:/usr/share/fscrawler/log4j2.properties:ro
    entrypoint: ["/bin/sh", "/root/.fscrawler/run_fscrawler.sh"]
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - es-net

  frontend:
    depends_on:
      pipeline-loader:
        condition: service_healthy
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
      es03:
        condition: service_healthy
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./elasticsearch/data/certs:/app/data/elasticsearch/certs
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - es-net

volumes:
  kibanadata:
    driver: local

networks:
  es-net:
    driver: bridge