name: "cohen"
fs:
  indexed_chars: 100%
  lang_detect: true
  continue_on_error: true
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
elasticsearch:
  nodes:
    - url: "http://elasticsearch:9200"
  username: "elastic"
  password: "changeme"
  ssl_verification: false
rest :
  url: "http://fscrawler:8080"
#elasticsearch:
#  index: "cohen"
#  index_folder: "cohen"
#rest :
#  url: "http://fscrawler:8080"
#fs:
#  url: "/usr/share/fscrawler/data"
#  update_rate: "15m"
#  excludes:
#    - "*/~*"
#    - "*.tmp"
#    - "*.temp"
#  json_support: false
#  filename_as_id: true
#  add_filesize: true
#  remove_deleted: true
#  store_source: false
#  index_content: true
#  attributes_support: false
#  raw_metadata: false
#  indexed_chars: -1
#  indexed_chars_field: "indexing"
#  ocr:
#    language: "eng"
#    enabled: true
#    pdf_strategy: "ocr_and_text"
#    ignore_robots_txt: true
#    pdftotext_options: ""
#    rotate_angle: 0
#    ignore_errors: false
#    output_type: "txt"
#    language_overrides:
#    rotate_pages: false
#    rotate_pages_threshold: 10
#  follow_symlinks: false
#  add_as_inner_object: false
#  indexed_chars_fieldname: "indexing"
#  attributes: []
#  xml_support: false
#  index_folders: true
#  lang_detect: false
#  continue_on_error: false
